apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: default
spec:
  containers:
  - name: event-simulator
    image: kodekloud/event-simulator
    volumeMounts:
    - name: vol
      mountPath: /log
  volumes:
  - name: vol
    hostPath:
      path: /var/log/webapp