apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 1G
    defaultRequest:
      memory: 1Gi
    type: Container
    max: 
      memory: 16Gi
    min:
      memory: 512Mi
    type: Container
