apiVersion: v1
kind: Pod
metadata: 
  name: my-two-conatiner-pod
  labels:
    app: my-two-container
    tier: helper-conatiner
spec:
  containers:
#    - name: nginx-conatiner
#      image: nginx
    - name: busybox-container
      image: busybox