apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - db/db-config.yaml
  - db/db-depl.yaml
  - db/db-service.yaml
  - message-broker/rabbitmq-config.yaml
  - message-broker/rabbitmq-depl.yaml
  - message-broker/rabbitmq-service.yaml
  - nginx/nginx-depl.yaml
  - nginx/nginx-service.yaml



# Common Transformers

# Labes
commonLables: 
  org: my-test-deployment

# Namepaces
namespace: dev-ns

# Name Prefix
namePrefix: qamar

# Name Subfix
nameSuffix: -dev

# Annotations
commonAnnotations:
  branch: master

# Change Image

images:
  - name: nginx
    newName: haproxy

# # Change Image Tag

# images:
#   - name: nginx
#     newTag: 2.4

# # Change Image name and Tag


# images:
#   - name: nginx
#     newName: haproxy
#     newTag: 2.4